---
title: "ML Models"
author: "EC4308 Group Project"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Conduct stratified sampling and loading the train and test sets
```{r}
# Set seed for reproducibility
set.seed(42)

hdb_data = readRDS("processed_data/hdb_resale_prices.RDS") 

# Stratified Sampling by 'year'
strata_cols <- c("year")

# Perform the stratified sampling for training set (20%)
train_data <- hdb_data %>%
  group_by(across(all_of(strata_cols))) %>%
  sample_frac(0.2) %>% # Adjust the fraction as needed for training set
  ungroup()

# Remaining data for test sets
test_data <- anti_join(hdb_data, train_data)

# from our EDA results, since we know that the distribution for the price variable is right skewed, we need to transform the price into log price to normalise

train_ml <- train_data %>% mutate(log_price = log(resale_price)) %>%
  select(-resale_price)

test_ml <- test_data %>% mutate(log_price = log(resale_price)) %>%
  select(-resale_price)
test_ml_y <- test_ml[,"log_price"]
test_ml <- test_ml %>%
  select(-log_price)
```

### Benchmark OLS model (Based on domain knowledge)
```{r}
set.seed(42)

# Based on domain knowledge, we picked a few variables that affect HDB prices
regfit = lm(formula= log_price ~ year + remaining_lease + floor_area_sqm + ave_storey +
           + dist_to_nearest_mrt + dist_to_nearest_primary_schools + dist_cbd,data=train_ml)

# Make predictions on the test data
predictions_ols <- predict(regfit, newdata = test_ml)
 
# Calculate RMSE
rmse_ols <- sqrt(mean((test_ml_y - predictions_ols)^2))
 
# Print RMSE
print(paste("RMSE for benchmark OLS:", rmse_ols))

summary(regfit)

# RMSE for benchmark OLS: 0.13494587838384
```

#Benchmark model
```{r}
# logistic regression
logit_model <- glm(am ~ mpg + hp + wt, data = mtcars, family = binomial(link = "logit"))
# display summary of the model
summary(logit_model)

# logistic LASSO regression
```

